#ifndef TYPE_OPERATIONS_TABLE
#define TYPE_OPERATIONS_TABLE

#include "Constants.h"

#include <string>
#include <unordered_map>
#include <vector>
#include <stdexcept>

typedef enum {
  INT = t_KEY_INT,
  FLOAT = t_KEY_FLOAT,
  DOUBLE = t_KEY_DOUBLE,
  CHAR = t_KEY_CHAR,
  VOID = t_KEY_VOID,
  STRING = t_KEY_STRING
} Type;

typedef enum {
  // OPERADORES ARITMETICOS
  SUM = t_KEY_PLUS,
  SUB = t_KEY_MINUS,
  MULTIPLY = t_KEY_MULTIPLY,
  DIVIDE = t_KEY_DIVIDE,
  MOD = t_KEY_MOD,
  OR = t_KEY_OR,
  AND = t_KEY_AND,
  BIT_OR = t_KEY_BIT_OR,
  BIT_AND = t_KEY_BIT_AND,
  SHIFT_LEFT = t_KEY_SHIFT_LEFT,
  SHIFT_RIGHT = t_KEY_SHIFT_RIGHT,

  // OPERADORES ATRIUICAO
  ASSIGN = t_KEY_ASSIGN,
  PLUS_ASSIGN = t_KEY_PLUS_ASSIGN,
  MINUS_ASSIGN = t_KEY_MINUS_ASSIGN,
  MULTIPLY_ASSIGN = t_KEY_MULTIPLY_ASSIGN,
  DIVIDE_ASSIGN = t_KEY_DIVIDE_ASSIGN,
  MOD_ASSIGN = t_KEY_MOD_ASSIGN,
  AND_ASSIGN = t_KEY_AND_ASSIGN,
  OR_ASSIGN = t_KEY_OR_ASSIGN,
  XOR_ASSIGN = t_KEY_XOR_ASSIGN,
  SHIFT_LEFT_ASSIGN = t_KEY_SHIFT_LEFT_ASSIGN,
  SHIFT_RIGHT_ASSIGN = t_KEY_SHIFT_RIGHT_ASSIGN
} Operator;

class TypeOperationsTable {
public:
  TypeOperationsTable() = default;

  static bool isCompatible(const std::string& left, const std::string& right, Operator op);

private:

  static Type stringToType(const std::string& str);

  inline static const std::unordered_map<Type, std::unordered_map<Type, std::vector<Operator>>> compatibleAtribuitionTypeTable = {
      {INT, {
          {INT,    {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}},
          {FLOAT,  {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}},
          {DOUBLE, {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}},
          {CHAR,   {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}}
      }},
      {FLOAT, {
          {INT,    {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}},
          {FLOAT,  {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}},
          {DOUBLE, {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}},
          {CHAR,   {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}}
      }},
      {DOUBLE, {
          {INT,    {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}},
          {FLOAT,  {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}},
          {DOUBLE, {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}},
          {CHAR,   {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}}
      }},
      {CHAR, {
          {CHAR,   {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}},
          {INT,    {SUM, SUB, MULTIPLY, DIVIDE, MOD, ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN}}
      }},
      {STRING, {
          {STRING, {SUM, ASSIGN, PLUS_ASSIGN}}
      }}
  };
};

#endif